/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'nirajmchauhan' at '3/9/17 8:30 AM' with Gradle 3.1
 *
 * @author nirajmchauhan, @date 3/9/17 8:30 AM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
